In [26]:
import pandas as pd
import numpy as np
import random
states = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
    "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
    "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
    "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
    "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
]

customers = pd.read_csv("Orders.csv")

customers['age'] = np.random.randint(20, 51, size=len(customers))
random_states = []
for s in range(len(customers)):
    random_states.append(random.choice(states))

customers['state'] = random_states

# newdf = customers.drop(columns = ['email','shoe_type','shoe_material','shoe_color','price'])
# display(newdf.head())

# newdf.to_csv("customers.csv")

# print(customers.age.median())
# print(customers.state.nunique())
# print(customers.state.unique())
# display(customers.head(5))
# display(customers.groupby('shoe_type').price.mean())
# display(customers.groupby('shoe_type').price.mean().reset_index())
# counts = customers.state.value_counts()
# display(counts)

# display(customers.groupby('shoe_type').age.apply(lambda x: np.percentile(x, 75)))

shoe_counts = customers.groupby(["shoe_type", "shoe_color"]).price.apply(lambda x: np.percentile(x, 30)).reset_index()
# display(shoe_counts)

shoe_counts.pivot(columns='shoe_type',
         index='shoe_color',
         values= 'price')
# display(shoe_counts)

shoe_counts2 = customers.groupby(["shoe_type", "age"]).id.count().reset_index()
shoe_counts2.pivot(columns = 'shoe_type', 
    index = 'age',
    values = 'id')

results = customers[(customers['shoe_type'] == 'ballet flats')]
display(results)

,id,first_name,last_name,email,shoe_type,shoe_material,shoe_color,price,age,state
0,41874,Kyle,Peck,KylePeck71@gmail.com,ballet flats,faux-leather,black,385.0,38,ME
9,54885,Carol,Mclaughlin,CM3415@gmail.com,ballet flats,faux-leather,brown,440.0,46,MI
10,35853,Jacob,Juarez,JJuarez1977@outlook.com,ballet flats,leather,red,331.0,48,MI
11,35916,Michael,Christensen,Michael.Christensen@gmail.com,ballet flats,faux-leather,red,270.0,39,CT
12,39587,Dennis,Vega,Dennis.Vega@gmail.com,ballet flats,faux-leather,brown,91.0,25,ID
14,19733,Deborah,Lara,Deborah.Lara@gmail.com,ballet flats,leather,white,205.0,26,NY
15,30871,Abigail,Dillard,ADillard1994@gmail.com,ballet flats,faux-leather,white,278.0,50,KY
18,35693,Margaret,Tyler,MTyler1974@gmail.com,ballet flats,fabric,brown,481.0,28,OR
53,10204,Victoria,Higgins,VictoriaHiggins66@hotmail.com,ballet flats,leather,red,187.0,34,PA
68,83346,Rachel,Lowery,Rachel.Lowery@gmail.com,ballet flats,faux-leather,brown,212.0,34,SD
70,55282,Noah,Knox,Noah.Knox@gmail.com,ballet flats,faux-leather,white,308.0,46,DE
71,33364,Andrea,Chang,Andrea.Chang@yahoo.com,ballet flats,faux-leather,white,106.0,36,OH
76,68967,Sharon,Franco,SFranco1983@gmail.com,ballet flats,fabric,brown,124.0,28,UT
80,93774,Rebecca,Park,RebeccaPark83@gmail.com,ballet flats,fabric,black,226.0,44,MO
91,83778,Joe,Perry,JoePerry3@gmail.com,ballet flats,leather,white,196.0,42,IA

In [36]:

visits = pd.read_csv("user_visits.csv", delimiter = "\t")
display(visits.head())

# source_counts = visits.utm_source.value_counts().reset_index()
# display(source_counts)

source_counts2 = visits.groupby('utm_source').id.count().reset_index()
print(source_counts2)

,id,first_name,last_name,email,month,utm_source
0,10043,Louis,Koch,LouisKoch43@gmail.com,3 - March,yahoo
1,10150,Bruce,Webb,BruceWebb44@outlook.com,3 - March,twitter
2,10155,Nicholas,Hoffman,Nicholas.Hoffman@gmail.com,2 - February,google
3,10178,William,Key,William.Key@outlook.com,3 - March,yahoo
4,10208,Karen,Bass,KB4971@gmail.com,2 - February,google

  utm_source   id
0      email  462
1   facebook  823
2     google  543
3    twitter  415
4      yahoo  757