In [2]:
import pandas as pd
rentals = pd.read_csv('rentals.csv', delimiter = '\t')
display(rentals)
rent = rentals['rent']
size = rentals.size_sqft
borough = rentals.borough
print(size.notna().sum())
print(size.isna().sum())
print(borough.unique())
print(borough.nunique())
size.mean()

print(rent.describe())

    rent  size_sqft    borough
0   2550        NaN  Manhattan
1  11500     2000.0  Manhattan
2   3000     1000.0     Queens
3   4500      916.0  Manhattan
4   4795      975.0  Manhattan

4
1
['Manhattan' 'Queens']
2
count        5.000000
mean      5269.000000
std       3611.880397
min       2550.000000
25%       3000.000000
50%       4500.000000
75%       4795.000000
max      11500.000000
Name: rent, dtype: float64

In [ ]:
movies = pd.read_csv('movies.csv', delimiter='\t')
display(movies.head())

min_production = movies["production_budget"].min()
max_production = movies["production_budget"].max()
range_production = max_production - min_production
display(range_production)

q1 = movies["production_budget"].quantile(0.25)  # Q1
q2 = movies["production_budget"].quantile(0.50)  # Q2 (Median)
q3 = movies["production_budget"].quantile(0.75)  # Q3
display(q1, q2, q3)

,movie,production_budget,domestic_gross,worldwide_gross,mpaa_rating,genre
0,Evan Almighty,175000000.0,100289690.0,1.741313e+08,PG,Comedy
1,Waterworld,175000000.0,88246220.0,2.642462e+08,PG-13,Action
2,King Arthur: Legend of the Sword,175000000.0,39175066.0,1.399507e+08,PG-13,Adventure
3,47 Ronin,175000000.0,38362475.0,1.517168e+08,PG-13,Action
4,Jurassic World: Fallen Kingdom,170000000.0,416769345.0,1.304866e+09,PG-13,Action

174750000.0

174750000.0

np.float64(9000000.0)

np.float64(20000000.0)

np.float64(45000000.0)