In [5]:
import pandas as pd
import numpy as np
import random
states = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
    "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
    "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
    "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
    "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
]

customers = pd.read_csv("Orders.csv")

customers['age'] = np.random.randint(20, 51, size=len(customers))
random_states = []
for s in range(len(customers)):
    random_states.append(random.choice(states))

customers['state'] = random_states

result = customers.groupby(['shoe_type', 'shoe_color']).id.count().reset_index()
display(result)

pivot_table = result.pivot(index = 'shoe_type', columns='shoe_color', values='id')
display(pivot_table)


# newdf = customers.drop(columns = ['email','shoe_type','shoe_material','shoe_color','price'])
# display(newdf.head())

# newdf.to_csv("customers.csv")

# print(customers.age.median())
# print(customers.state.nunique())
# print(customers.state.unique())
# display(customers.head(5))
# display(customers.groupby('shoe_type').price.mean())
# display(customers.groupby('shoe_type').price.mean().reset_index())
# counts = customers.state.value_counts()
# display(counts)

# display(customers.groupby('shoe_type').age.apply(lambda x: np.percentile(x, 75)))

# shoe_counts = customers.groupby(["shoe_type", "shoe_color"]).count()
# display(shoe_counts)

# pivot1_data = customers.groupby(['shoe_type', 'shoe_color']).id.count().reset_index()
# pivot_table1 = pivot1_data.pivot(
#     index='shoe_type',
#     columns='shoe_color',
#     values='id'
# )
# display(pivot_table1)

# pivot2_data = customers.groupby(['shoe_type', 'shoe_color']).price.mean().reset_index()
# pivot_table2 = pivot2_data.pivot(
#     index = 'shoe_type',
#     columns = 'shoe_color',
#     values = 'price'
# )
# display(pivot_table2)

# pivot3_data = customers.groupby(["shoe_type", "shoe_color"]).price.apply(lambda x: np.percentile(x, 30)).reset_index()
# pivot_table3 = pivot3_data.pivot(
#     index = 'shoe_type',
#     columns = 'shoe_color',
#     values = 'price'
# )
# display(pivot_table3)


# shoe_counts.pivot(columns='shoe_type',
#          index='shoe_color',
#          values= 'price')
# display(shoe_counts)

# shoe_counts2 = customers.groupby(["shoe_type", "age"]).id.count().reset_index()
# shoe_counts2.pivot(columns = 'shoe_type', 
#     index = 'age',
#     values = 'id')

# results = customers[(customers['shoe_type'] == 'ballet flats')]
# display(results)

       shoe_type shoe_color  id
0   ballet flats      black   2
1   ballet flats      brown   5
2   ballet flats        red   3
3   ballet flats      white   5
4          boots      black   3
5          boots      brown   5
6          boots       navy   6
7          boots        red   2
8          boots      white   3
9          clogs      black   4
10         clogs      brown   6
11         clogs       navy   1
12         clogs        red   4
13         clogs      white   1
14       sandals      black   1
15       sandals      brown   4
16       sandals       navy   5
17       sandals        red   3
18       sandals      white   4
19     stilettos      black   5
20     stilettos      brown   3
21     stilettos       navy   2
22     stilettos        red   2
23     stilettos      white   2
24        wedges      black   3
25        wedges      brown   4
26        wedges       navy   4
27        wedges        red   5
28        wedges      white   2

shoe_color    black  brown  navy  red  white
shoe_type
ballet flats    2.0    5.0   NaN  3.0    5.0
boots           3.0    5.0   6.0  2.0    3.0
clogs           4.0    6.0   1.0  4.0    1.0
sandals         1.0    4.0   5.0  3.0    4.0
stilettos       5.0    3.0   2.0  2.0    2.0
wedges          3.0    4.0   4.0  5.0    2.0

In [36]:

visits = pd.read_csv("user_visits.csv", delimiter = "\t")
display(visits.head())

# source_counts = visits.utm_source.value_counts().reset_index()
# display(source_counts)

source_counts2 = visits.groupby('utm_source').id.count().reset_index()
print(source_counts2)

,id,first_name,last_name,email,month,utm_source
0,10043,Louis,Koch,LouisKoch43@gmail.com,3 - March,yahoo
1,10150,Bruce,Webb,BruceWebb44@outlook.com,3 - March,twitter
2,10155,Nicholas,Hoffman,Nicholas.Hoffman@gmail.com,2 - February,google
3,10178,William,Key,William.Key@outlook.com,3 - March,yahoo
4,10208,Karen,Bass,KB4971@gmail.com,2 - February,google

  utm_source   id
0      email  462
1   facebook  823
2     google  543
3    twitter  415
4      yahoo  757