In [1]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency   

npi = pd.read_csv("data.csv", delimiter= "\t")
display(npi.head())

# Creates a cross table of counts
contingency_table = pd.crosstab(npi['influence'], npi['leader'])

chi2, p, dof, expected = chi2_contingency(contingency_table)
# Displays the expected counts
display(np.round(expected))
display(np.round(chi2))



# chi2, pval, dof, expected = chi2_contingency(influence_leader_freq)
# print(np.round(expected))

  influence blend_in special leader authority
0        no      yes     yes    yes       yes
1        no      yes      no     no        no
2       yes       no     yes    yes       yes
3       yes       no      no    yes       yes
4       yes      yes      no    yes        no

array([[2087., 2221.],
       [3288., 3501.]])

np.float64(1308.0)

In [7]:
titanic = pd.read_csv('titanic.csv')
display(titanic.head())

crosstab_counts = pd.crosstab(titanic['Sex'], titanic['Survived'])
display(crosstab_counts)
crosstab_proportions = crosstab_counts/len(titanic)
display(crosstab_proportions)
display(len(titanic))

chi2, p, dof, expected = chi2_contingency(crosstab_counts)
# Displays the expected counts
display(np.round(expected))
display(chi2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Survived    0    1
Sex
female     81  233
male      468  109

Survived         0         1
Sex
female    0.090909  0.261504
male      0.525253  0.122334

891

array([[193., 121.],
       [356., 221.]])

np.float64(260.71702016732104)