In [2]:
import pandas as pd
df = pd.read_csv("TheHandyWoman.csv", delimiter = "\t")
display(df)
df['Quantity'] = [100, 150, 50, 35]
df['In Stock?'] = True
df['Sales Tax'] = df.Price * 0.075


display(df)

   Product ID Product Description  Cost to Manufacture  Price
0           1        3 inch screw                  0.5   0.75
1           2         2 inch nail                  0.1   0.25
2           3              hammer                  3.0   5.50
3           4         screwdriver                  2.5   3.00

,Product ID,Product Description,Cost to Manufacture,Price,Quantity,In Stock?,Sales Tax
0,1,3 inch screw,0.5,0.75,100,True,0.05625
1,2,2 inch nail,0.1,0.25,150,True,0.01875
2,3,hammer,3.0,5.50,50,True,0.41250
3,4,screwdriver,2.5,3.00,35,True,0.22500

In [5]:
df = pd.read_csv("Customers.csv", delimiter = "\t")
df['Name'] = df['Name'].apply(str.upper)

provider = lambda e: e.split("@")[1]
df['Provider'] = df['Email'].apply(provider)
display(df)


# df['Lowercase Name'] = df['Name'].apply(str.lower)
# display(df)

         Name                 Email     Provider
0  JOHN SMITH  john.smith@gmail.com    gmail.com
1    JANE DOE        jdoe@yahoo.com    yahoo.com
2   JOE SCHMO  joeschmo@hotmail.com  hotmail.com

In [ ]:
add_two = lambda my_input: my_input + 2

# print(add_two(3))
# print(add_two(100))
# print(add_two(-2))

is_substring = lambda my_string: my_string in "This is the master string"

print(is_substring('I'))
print(is_substring('am'))
print(is_substring('the'))
print(is_substring('master'))

check_if_A_grade = lambda grade: 'Got an A!' if grade >= 90 else 'Did not get an A...'

print(check_if_A_grade(89))

False
False
True
True

'Did not get an A...'

In [24]:
df = pd.read_csv("Employees.csv", delimiter = "\t")
display(df)

# total_earned = lambda row: (row.hourly_wage * 40) + ((row.hourly_wage * 1.5) * (row.hours_worked - 40)) \
# 	if row.hours_worked > 40 \
#   else row.hourly_wage * row.hours_worked
  
# df['total_earned'] = df.apply(total_earned)

adj_hours = lambda h: 40 + (h - 40) * 1.5 if h > 40 else h

df['adj_hours'] = df['hours_worked'].apply(adj_hours)

df['earnings'] = df['adj_hours'] * df['hourly_wage']
display(df)

    Unnamed: 0     id               name  hourly_wage  hours_worked
0            0  10310      Lauren Durham           19            43
1            1  18656      Grace Sellers           17            40
2            2  61254  Shirley Rasmussen           16            30
3            3  16886        Brian Rojas           18            47
4            4  89010    Samantha Mosley           11            38
5            5  87246       Louis Guzman           14            39
6            6  20578     Denise Mcclure           15            40
7            7  12869      James Raymond           15            32
8            8  53461       Noah Collier           18            35
9            9  14746    Donna Frederick           20            41
10          10  71127       Shirley Beck           14            32
11          11  92522    Christina Kelly            8            44
12          12  22447        Brian Noble           11            39
13          13  61654          Randy Key           16            38
14          14  16988      Diana Stewart           14            48
15          15  68619       Timothy Sosa           14            42
16          16  59949      Betty Skinner           11            48
17          17  81418      Janet Maxwell           12            38
18          18  27267   Madison Johnston           20            37
19          19  19985   Virginia Nichols           13            49

,Unnamed: 0,id,name,hourly_wage,hours_worked,adj_hours,earnings
0,0,10310,Lauren Durham,19,43,44.5,845.5
1,1,18656,Grace Sellers,17,40,40.0,680.0
2,2,61254,Shirley Rasmussen,16,30,30.0,480.0
3,3,16886,Brian Rojas,18,47,50.5,909.0
4,4,89010,Samantha Mosley,11,38,38.0,418.0
5,5,87246,Louis Guzman,14,39,39.0,546.0
6,6,20578,Denise Mcclure,15,40,40.0,600.0
7,7,12869,James Raymond,15,32,32.0,480.0
8,8,53461,Noah Collier,18,35,35.0,630.0
9,9,14746,Donna Frederick,20,41,41.5,830.0
10,10,71127,Shirley Beck,14,32,32.0,448.0
11,11,92522,Christina Kelly,8,44,46.0,368.0
12,12,22447,Brian Noble,11,39,39.0,429.0
13,13,61654,Randy Key,16,38,38.0,608.0
14,14,16988,Diana Stewart,14,48,52.0,728.0
15,15,68619,Timothy Sosa,14,42,43.0,602.0
16,16,59949,Betty Skinner,11,48,52.0,572.0
17,17,81418,Janet Maxwell,12,38,38.0,456.0
18,18,27267,Madison Johnston,20,37,37.0,740.0
19,19,19985,Virginia Nichols,13,49,53.5,695.5

In [2]:
import pandas as pd
df = pd.DataFrame({
    'name': ['John', 'Jane', 'Sue', 'Fred'],
    'age': [23, 29, 21, 18]
})
display(df)
df.columns = ['First Name', 'Age']
display(df)


# df = pd.DataFrame({
#     'name': ['John', 'Jane', 'Sue', 'Fred'],
#     'age': [23, 29, 21, 18]
# })
# df.rename(columns={
#     'name': 'First Name',
#     'age': 'Age'},
#     inplace=True)

# display(df)

   name  age
0  John   23
1  Jane   29
2   Sue   21
3  Fred   18

  First Name  Age
0       John   23
1       Jane   29
2        Sue   21
3       Fred   18

In [10]:
df = pd.read_csv("GroceryItems.csv", delimiter = "\t")
display(df)

           Item  Price Is taxed?
0         Apple   1.00        No
1          Milk   4.20        No
2  Paper Towels   5.00       Yes
3   Light Bulbs   3.75       Yes

In [58]:
df = pd.read_csv("Movies.csv")
# display(df)

df.rename(columns = {"movie_title":"name","imdb_rating":"rating"}, inplace = True)
display(df.head())

   id                                       name   genre  year  rating
0   1                                     Avatar  action  2009     7.9
1   2                             Jurassic World  action  2015     7.3
2   3                               The Avengers  action  2012     8.1
3   4                            The Dark Knight  action  2008     9.0
4   5  Star Wars: Episode I - The Phantom Menace  action  1999     6.6